version: "3.3"
services:
  gotrue:
    build: .
    image: gotrue
    container_name: gotrue
    ports:
      - 8082:8082
    networks: 
      - app-network
    environment:
      - GOTRUE_JWT_SECRET=secret-key-shared-between-git-gateway-and-gotrue
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_AUD=
      - GOTRUE_DB_DRIVER=mysql
      # - DATABASE_URL="root:@tcp(127.0.0.1:3306)/gotrue?parseTime=true&multiStatements=true"
      - DATABASE_URL=uqfile0k_gotrue:I6vuNGbGvmZA@tcp(194.233.77.193:3306)/uqfile0k_test?parseTime=true&multiStatements=true
      - GOTRUE_API_HOST=0.0.0.0
      - PORT=8082
      - GOTRUE_SITE_URL=https://example.com
      - GOTRUE_LOG_LEVEL=DEBUG
      - GOTRUE_OPERATOR_TOKEN=super-secret-operator-token
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_SMTP_HOST=
      - GOTRUE_SMTP_PORT=12
      - GOTRUE_SMTP_USER=
      - GOTRUE_SMTP_PASS=
      - GOTRUE_SMTP_ADMIN_EMAIL=
      - GOTRUE_MAILER_SUBJECTS_CONFIRMATION="Welcome to GoTrue!"
      - GOTRUE_MAILER_SUBJECTS_RECOVERY="Reset your GoTrue password!"
  
  proxy:
    image: nginx:alpine
    container_name: web-proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - gotrue
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
